server:
  port: 8080

spring:
  application:
    name: gateway-service

---
spring:
  config:
    activate:
      on-profile: default

  cloud:
    gateway:
      routes:
        - id: author-route
          uri: http://localhost:8081
          predicates:
            - Path=/authors/**

        - id: book-route
          uri: http://localhost:8080
          predicates:
            - Path=/books/**

        - id: member-route
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /users/${segment}

server:
  port: 9000

---
spring:
  config:
    activate:
      on-profile: docker

  cloud:
    gateway:
      routes:
        - id: author-route
          uri: http://author:8080
          predicates:
            - Path=/authors/**

        - id: book-route
          uri: http://book:8080
          predicates:
            - Path=/books/**

        - id: member-route
          uri: http://member:8080
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /users/${segment}
