server:
  port: 8080

# OpenAI API 키를 여기에 직접 입력하거나 환경 변수로 설정할 수 있습니다.
openai:
  api:
    key: # <-- 아무런 의미 없는 임시 텍스트 키를 직접 입력

---
# 'default' 프로필 설정 (로컬 개발 환경)
spring:
  config:
    activate:
      on-profile: default

  # --- 이 부분을 새로 추가하거나, 기존 datasource/h2 설정을 교체합니다 ---
  h2:
    console:
      enabled: true           # H2 콘솔 기능을 켭니다.
      path: /h2-console       # 콘솔 접속 경로입니다.
  datasource:
    url: jdbc:h2:mem:bookdb   # book 서비스의 DB에 'bookdb'라는 고정된 이름을 부여합니다.
    driverClassName: org.h2.Driver
    username: sa
    password:
  # ---------------------------------------------------------------------

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 Entity에 맞춰 테이블을 자동으로 변경/생성

  cloud:
    function:
      definition: bookEventConsumer;wheneverBookAccessChecked_Route
    stream:
      bindings:
        bookEventConsumer-in-0:
          destination: book.topic
          group: book
          contentType: application/json
        wheneverBookAccessChecked_Route-in-0:
          destination: book.topic
          group: book
          consumer:
            condition: "headers['type']=='BookAccessChecked'"
        bookEventProducer-out-0:
          destination: book.topic
      kafka:
        binder:
          brokers: localhost:9092

---
# 'docker' 프로필 설정 (도커 컨테이너 환경)
spring:
  config:
    activate:
      on-profile: docker

  # 도커 환경에서는 H2 대신 실제 DB(예: PostgreSQL, MySQL)를 사용하도록
  # 여기에 datasource 설정을 추가할 수 있습니다. 지금은 비워둡니다.

  cloud:
    function:
      definition: bookEventConsumer;wheneverBookAccessChecked_Route
    stream:
      bindings:
        bookEventConsumer-in-0:
          destination: book.topic
          group: book
          contentType: application/json
        wheneverBookAccessChecked_Route-in-0:
          destination: book.topic
          group: book
          consumer:
            condition: "headers['type']=='BookAccessChecked'"
        bookEventProducer-out-0:
          destination: book.topic
      kafka:
        binder:
          brokers: my-kafka:9092