### 1. 새로운 작가 등록 신청하기
# '제인'이라는 이름의 새로운 작가가 등록을 신청합니다.
POST http://localhost:8081/authors/register
Content-Type: application/json

{
  "name": "제인",
  "description": "판타지 소설을 씁니다.",
  "portfolio": "https://jane-doe.blog"
}


### 2. 작가 승인하기 (ID는 1번 실행 후 채워넣어야 합니다)
# 위에서 신청한 작가를 승인합니다.
POST http://localhost:8081/authors/여기에-ID-붙여넣기/approve